[package]
name = "atosdds"
version = "0.0.1"
authors = [""]
description = "DSS implementation with RTPS"
readme = "README.md"
keywords = ["protocol"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
time = "0.1.39"
bytes = "0.5.4"
mio = "0.6.22"
mio-extras = "2.0"
tokio-util = { version = "0.3.1", features = ["codec"] }
bit-set = "0.5.2"
bit-vec = "0.6.2"
speedy = "0.6.0"
log = "0.4.8"
num-traits = "0.2"
num-derive = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_repr = {version = "0.1" }
byteorder = "1"
uuid = { version = "0.8.1", features = ["v4"] }
rand = "0.7.3"
timer = "0.1"
chrono = "0.2"
enumflags2 = "0.6"
num_enum = "0.5.1"
get_if_addrs = "0.5.3"
