// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UInt8Type.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "UInt8Type.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

UInt8Type::UInt8Type()
{
    // m_value com.eprosima.idl.parser.typecode.PrimitiveTypeCode@cb0ed20
    m_value = 0;

}

UInt8Type::~UInt8Type()
{
}

UInt8Type::UInt8Type(
        const UInt8Type& x)
{
    m_value = x.m_value;
}

UInt8Type::UInt8Type(
        UInt8Type&& x)
{
    m_value = x.m_value;
}

UInt8Type& UInt8Type::operator =(
        const UInt8Type& x)
{

    m_value = x.m_value;

    return *this;
}

UInt8Type& UInt8Type::operator =(
        UInt8Type&& x)
{

    m_value = x.m_value;

    return *this;
}

bool UInt8Type::operator ==(
        const UInt8Type& x) const
{

    return (m_value == x.m_value);
}

bool UInt8Type::operator !=(
        const UInt8Type& x) const
{
    return !(*this == x);
}

size_t UInt8Type::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t UInt8Type::getCdrSerializedSize(
        const UInt8Type& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void UInt8Type::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_value;

}

void UInt8Type::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_value;
}

/*!
 * @brief This function sets a value in member value
 * @param _value New value for member value
 */
void UInt8Type::value(
        uint8_t _value)
{
    m_value = _value;
}

/*!
 * @brief This function returns the value of member value
 * @return Value of member value
 */
uint8_t UInt8Type::value() const
{
    return m_value;
}

/*!
 * @brief This function returns a reference to member value
 * @return Reference to member value
 */
uint8_t& UInt8Type::value()
{
    return m_value;
}


size_t UInt8Type::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool UInt8Type::isKeyDefined()
{
    return false;
}

void UInt8Type::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}
