struct NetboxMessageL {
    @key
    //string data;
    sequence<uint16> data; // Adjust size as necessary

    //uint8 data[16];

};
/*
struct NetboxMessage {
    @key
    uint64 id;
    sequence<string> topics;
    uint64 timestamp;
    sequence<uint8> payload;
};*/
