// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UInt8Type.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_UINT8TYPE_H_
#define _FAST_DDS_GENERATED_UINT8TYPE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UINT8TYPE_SOURCE)
#define UINT8TYPE_DllAPI __declspec( dllexport )
#else
#define UINT8TYPE_DllAPI __declspec( dllimport )
#endif // UINT8TYPE_SOURCE
#else
#define UINT8TYPE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UINT8TYPE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure UInt8Type defined by the user in the IDL file.
 * @ingroup UInt8Type
 */
class UInt8Type
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport UInt8Type();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~UInt8Type();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object UInt8Type that will be copied.
     */
    eProsima_user_DllExport UInt8Type(
            const UInt8Type& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object UInt8Type that will be copied.
     */
    eProsima_user_DllExport UInt8Type(
            UInt8Type&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object UInt8Type that will be copied.
     */
    eProsima_user_DllExport UInt8Type& operator =(
            const UInt8Type& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object UInt8Type that will be copied.
     */
    eProsima_user_DllExport UInt8Type& operator =(
            UInt8Type&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x UInt8Type object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const UInt8Type& x) const;

    /*!
     * @brief Comparison operator.
     * @param x UInt8Type object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const UInt8Type& x) const;

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            uint8_t _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport uint8_t value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport uint8_t& value();

private:

    uint8_t m_value{0};

};

#endif // _FAST_DDS_GENERATED_UINT8TYPE_H_



