/*module Type1 {
struct NetboxMessage {
        uint16 id;
        sequence<string> topics;
        uint64 timestamp;
        sequence<uint8> payload;
};
};
*/
/*module Type2 {
    struct NetboxMessage {
        uint8 id;
        sequence<uint8> data;
    };
};*/
/*struct NetboxMessage {
    @key
    uint8 id;            // Change from uint64 to uint8
    sequence<uint8> data; // Adjust size as necessary
};*/

struct NetboxMessage1 {
    @key 
    int64 id;
    sequence<string> topics;
    uint64 timestamp;
    sequence<uint8> payload;
};



