// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file newmessage.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "newmessage.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>






NetboxMessage::NetboxMessage()
{
}

NetboxMessage::~NetboxMessage()
{
}

NetboxMessage::NetboxMessage(
        const NetboxMessage& x)
{
    m_id = x.m_id;
    m_topics = x.m_topics;
    m_timestamp = x.m_timestamp;
    m_payload = x.m_payload;
}

NetboxMessage::NetboxMessage(
        NetboxMessage&& x) noexcept
{
    m_id = x.m_id;
    m_topics = std::move(x.m_topics);
    m_timestamp = x.m_timestamp;
    m_payload = std::move(x.m_payload);
}

NetboxMessage& NetboxMessage::operator =(
        const NetboxMessage& x)
{

    m_id = x.m_id;
    m_topics = x.m_topics;
    m_timestamp = x.m_timestamp;
    m_payload = x.m_payload;
    return *this;
}

NetboxMessage& NetboxMessage::operator =(
        NetboxMessage&& x) noexcept
{

    m_id = x.m_id;
    m_topics = std::move(x.m_topics);
    m_timestamp = x.m_timestamp;
    m_payload = std::move(x.m_payload);
    return *this;
}

bool NetboxMessage::operator ==(
        const NetboxMessage& x) const
{
    return (m_id == x.m_id &&
           m_topics == x.m_topics &&
           m_timestamp == x.m_timestamp &&
           m_payload == x.m_payload);
}

bool NetboxMessage::operator !=(
        const NetboxMessage& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void NetboxMessage::id(
        uint16_t _id)
{
    m_id = _id;
}

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
uint16_t NetboxMessage::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
uint16_t& NetboxMessage::id()
{
    return m_id;
}


/*!
 * @brief This function copies the value in member topics
 * @param _topics New value to be copied in member topics
 */
void NetboxMessage::topics(
        const std::vector<std::string>& _topics)
{
    m_topics = _topics;
}

/*!
 * @brief This function moves the value in member topics
 * @param _topics New value to be moved in member topics
 */
void NetboxMessage::topics(
        std::vector<std::string>&& _topics)
{
    m_topics = std::move(_topics);
}

/*!
 * @brief This function returns a constant reference to member topics
 * @return Constant reference to member topics
 */
const std::vector<std::string>& NetboxMessage::topics() const
{
    return m_topics;
}

/*!
 * @brief This function returns a reference to member topics
 * @return Reference to member topics
 */
std::vector<std::string>& NetboxMessage::topics()
{
    return m_topics;
}


/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void NetboxMessage::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t NetboxMessage::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& NetboxMessage::timestamp()
{
    return m_timestamp;
}


/*!
 * @brief This function copies the value in member payload
 * @param _payload New value to be copied in member payload
 */
void NetboxMessage::payload(
        const std::vector<uint8_t>& _payload)
{
    m_payload = _payload;
}

/*!
 * @brief This function moves the value in member payload
 * @param _payload New value to be moved in member payload
 */
void NetboxMessage::payload(
        std::vector<uint8_t>&& _payload)
{
    m_payload = std::move(_payload);
}

/*!
 * @brief This function returns a constant reference to member payload
 * @return Constant reference to member payload
 */
const std::vector<uint8_t>& NetboxMessage::payload() const
{
    return m_payload;
}

/*!
 * @brief This function returns a reference to member payload
 * @return Reference to member payload
 */
std::vector<uint8_t>& NetboxMessage::payload()
{
    return m_payload;
}


// Include auxiliary functions like for serializing/deserializing.
#include "newmessageCdrAux.ipp"

